CREATE TABLE localizacao
(
    id        int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    latitude  float8 NULL,
    longitude float8 NULL,
    CONSTRAINT localizacao_pKey PRIMARY KEY (id)
);

CREATE TABLE restaurante
(
    id             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome           varchar(50) NULL,
    localizacao_id int8 NOT NULL,
    CONSTRAINT restaurante_pKey PRIMARY KEY (id)
);

ALTER TABLE restaurante
    ADD CONSTRAINT res_loc FOREIGN KEY (localizacao_id) REFERENCES localizacao (id);

CREATE TABLE prato
(
    id             int8           NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    descricao      varchar(50) NULL,
    nome           varchar(50) NULL,
    preco          numeric(19, 2) NOT NULL,
    restaurante_id int8           NOT NULL,
    CONSTRAINT prato_pKey PRIMARY KEY (id)
);

ALTER TABLE prato
    ADD CONSTRAINT pra_res FOREIGN KEY (restaurante_id) REFERENCES restaurante (id);

CREATE TABLE prato_carrinho
(
    prato   int NULL,
    usuario varchar(200)
);

INSERT INTO localizacao(id, latitude, longitude)
VALUES (1000, -15.65454, -47.2545454);

INSERT INTO restaurante(id, nome, localizacao_id) VALUES (999, 'Manguai', 1000);

INSERT INTO prato(id, nome, descricao, preco, restaurante_id)
VALUES (9998, 'Cuscuz com ovo', 'Bom demais no café', 3.99, 999);

INSERT INTO prato(id, nome, descricao, preco, restaurante_id)
VALUES (9997, 'Peixe frito', 'Agulhinha frita, excelente com cerveja', 99.99, 999);
